### ISSUE TITLE
Can we have unit tests?

### ISSUE THREAD

**Issue by miraage** [baphomet-berlin/jQuery-basic-arithmetic-plugin#12] opened 2016-07-08 11:47 UTC
To ensure, that code is rock solid, there are should be unit tests.

**Comment by strugee** [comment] 2016-07-13 07:12
Duplicate of #6?

**Closed** 2016-07-13 09:15 UTC

**Comment by cbrandolino** [comment] 2016-07-13 10:37
guys you are the best community i ever saw around any open source project; just --- thank you.
